# Generated by Django 3.0.3 on 2020-02-25 11:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
